# Generated by Django 4.2.5 on 2023-09-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("game", "0001_initial"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=800)),
                (
                    "type_1",
                    models.CharField(
                        choices=[
                            (1, "fire"),
                            (2, "water"),
                            (3, "grass"),
                            (4, "electric"),
                            (5, "ice"),
                            (6, "poison"),
                            (7, "ground"),
                            (8, "dark"),
                            (9, "steal"),
                            (10, "fairy"),
                            (11, "normal"),
                        ],
                        default=11,
                        max_length=2,
                    ),
                ),
                (
                    "type_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            (1, "fire"),
                            (2, "water"),
                            (3, "grass"),
                            (4, "electric"),
                            (5, "ice"),
                            (6, "poison"),
                            (7, "ground"),
                            (8, "dark"),
                            (9, "steal"),
                            (10, "fairy"),
                            (11, "normal"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("damage", models.IntegerField(blank=True, null=True)),
                ("health", models.IntegerField(blank=True, null=True)),
                ("rarity", models.IntegerField(default=0)),
                ("probability", models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="moves", to="game.set"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlugManager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="slugs", to="dashboard.dashboard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSlug",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pet_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            (1, "red"),
                            (2, "green"),
                            (3, "blue"),
                            (4, "yellow"),
                            (5, "orange"),
                            (6, "pink"),
                            (7, "purple"),
                            (8, "white"),
                        ],
                        default=1,
                        max_length=2,
                    ),
                ),
                ("exp", models.IntegerField(default=0)),
                ("lvl", models.IntegerField(default=0)),
                ("in_battle", models.BooleanField(blank=True, default=False, null=True)),
                ("favorite", models.BooleanField(blank=True, default=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slugs",
                        to="pets.slugmanager",
                    ),
                ),
                ("moves", models.ManyToManyField(blank=True, related_name="slugs", to="pets.move")),
            ],
        ),
        migrations.CreateModel(
            name="Slug",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "type_1",
                    models.CharField(
                        choices=[
                            (1, "fire"),
                            (2, "water"),
                            (3, "grass"),
                            (4, "electric"),
                            (5, "ice"),
                            (6, "poison"),
                            (7, "ground"),
                            (8, "dark"),
                            (9, "steal"),
                            (10, "fairy"),
                            (11, "normal"),
                        ],
                        default=11,
                        max_length=2,
                    ),
                ),
                (
                    "type_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            (1, "fire"),
                            (2, "water"),
                            (3, "grass"),
                            (4, "electric"),
                            (5, "ice"),
                            (6, "poison"),
                            (7, "ground"),
                            (8, "dark"),
                            (9, "steal"),
                            (10, "fairy"),
                            (11, "normal"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("rarity", models.IntegerField(default=0)),
                ("probability", models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="slugs", to="game.set"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hp_now", models.IntegerField(default=0)),
                ("hp_total", models.IntegerField(default=0)),
                ("attack", models.IntegerField(default=0)),
                ("defense", models.IntegerField(default=0)),
                ("speed", models.IntegerField(default=0)),
                ("special_attack", models.IntegerField(default=0)),
                ("special_defense", models.IntegerField(default=0)),
                ("accuracy", models.IntegerField(default=0)),
                ("evasion", models.IntegerField(default=0)),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stats", to="pets.userslug"
                    ),
                ),
            ],
        ),
    ]
