# Generated by Django 4.2.5 on 2023-11-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userslug",
            name="color",
            field=models.CharField(
                choices=[
                    (1, "red"),
                    (2, "green"),
                    (3, "blue"),
                    (4, "yellow"),
                    (5, "orange"),
                    (6, "pink"),
                    (7, "purple"),
                    (8, "white"),
                    (9, "black"),
                    (10, "Silver"),
                    (11, "gold"),
                ],
                default=1,
                max_length=2,
            ),
        ),
    ]
