# Generated by Django 4.2.5 on 2023-09-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        ("game", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="dashboard.dashboard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=400)),
                ("value", models.IntegerField(default=0)),
                ("rarity", models.IntegerField(default=0)),
                ("probability", models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("retired_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="items", to="game.set"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shop", to="dashboard.dashboard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("in_shop", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="items.inventory"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="owned", to="items.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChestItem",
            fields=[
                (
                    "useritem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="items.useritem",
                    ),
                ),
                ("random_number", models.IntegerField(default=2)),
            ],
            bases=("items.useritem",),
        ),
        migrations.CreateModel(
            name="ConsumeItem",
            fields=[
                (
                    "useritem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="items.useritem",
                    ),
                ),
                ("action", models.CharField(choices=[(1, "heal"), (2, "exp up")], max_length=2)),
                ("amount", models.IntegerField()),
            ],
            bases=("items.useritem",),
        ),
        migrations.CreateModel(
            name="CurrencyItem",
            fields=[
                (
                    "useritem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="items.useritem",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
            ],
            bases=("items.useritem",),
        ),
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.IntegerField(default=0)),
                ("in_market", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="for_sale",
                        to="items.useritem",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shop", to="items.shop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlugItem",
            fields=[
                (
                    "useritem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="items.useritem",
                    ),
                ),
                ("chest", models.BooleanField(default=True)),
                (
                    "slug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itemized",
                        to="pets.userslug",
                    ),
                ),
            ],
            bases=("items.useritem",),
        ),
        migrations.CreateModel(
            name="MoveItem",
            fields=[
                (
                    "useritem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="items.useritem",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="itemized", to="pets.move"
                    ),
                ),
            ],
            bases=("items.useritem",),
        ),
    ]
