# Generated by Django 4.2.5 on 2023-09-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0002_setting_delete_battlemanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleManager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dashboard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="battles", to="dashboard.dashboard"
                    ),
                ),
            ],
        ),
    ]
